[package]
name = "geojson_example"
version = "0.1.0"
authors = ["Stephan Hügel <urschrei@gmail.com>"]

[dependencies]
geo = "0.6.2"
geojson = "0.9.1"
serde_json = "1.0.8"

[[bin]]
name = "example"
path = "src/main.rs"
crate-type = ["bin"]
