[package]
name = "geojson_example"
version = "0.1.0"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/urschrei/geojson_example"
keywords = ["geo", "geojson", "gis"]

[dependencies]
geo = "0.6.2"
geojson = "0.9.1"
serde_json = "1.0.8"
rayon = "0.9.0"

[[bin]]
name = "borrowed"
path = "src/borrowed.rs"
crate-type = ["bin"]

[[bin]]
name = "owned"
path = "src/owned.rs"
crate-type = ["bin"]
